[versions]
kafka = "4.1.0"
confluent = "8.1.0"
junit = "5.14.1"
mockito = "5.20.0"

[libraries]
kafka-clients = { group = "org.apache.kafka", name = "kafka-clients", version.ref = "kafka" }
kafka-core = { group = "org.apache.kafka", name = "kafka_2.13", version.ref = "kafka" }
kafka-server = { group = "org.apache.kafka", name = "kafka-server", version.ref = "kafka" }
kafka-server-common = { group = "org.apache.kafka", name = "kafka-server-common", version.ref = "kafka" }
kafka-test-common-runtime = { group = "org.apache.kafka", name = "kafka-test-common-runtime", version.ref = "kafka" }
kafka-group-coordinator = { group = "org.apache.kafka", name = "kafka-group-coordinator", version.ref = "kafka" }
kafka-streams = { group = "org.apache.kafka", name = "kafka-streams", version.ref = "kafka" }
kafka-streams-test-utils = { group = "org.apache.kafka", name = "kafka-streams-test-utils", version.ref = "kafka" }
kafka-tools = { group = "org.apache.kafka", name = "kafka-tools", version.ref = "kafka" }
kafka-connect-api = { group = "org.apache.kafka", name = "connect-api", version.ref = "kafka" }
kafka-connect-transforms = { group = "org.apache.kafka", name = "connect-transforms", version.ref = "kafka" }
kafka-connect-runtime = { group = "org.apache.kafka", name = "connect-runtime", version.ref = "kafka" }
kafka-connect-json = { group = "org.apache.kafka", name = "connect-json", version.ref = "kafka" }
kafka-connect-file = { group = "org.apache.kafka", name = "connect-file", version.ref = "kafka" }
kafka-schema-serializer = { group = "io.confluent", name = "kafka-schema-serializer", version.ref = "confluent" }
kafka-schema-registry-client = { group = "io.confluent", name = "kafka-schema-registry-client", version.ref = "confluent" }
kafka-avro-serializer = { group = "io.confluent", name = "kafka-avro-serializer", version.ref = "confluent" }
kafka-protobuf-serializer = { group = "io.confluent", name = "kafka-protobuf-serializer", version.ref = "confluent" }
kafka-protobuf-provider = { group = "io.confluent", name = "kafka-protobuf-provider", version.ref = "confluent" }
kafka-jsonSchema-serializer = { group = "io.confluent", name = "kafka-json-schema-serializer", version.ref = "confluent" }
kafka-jsonSchema-provider = { group = "io.confluent", name = "kafka-json-schema-provider", version.ref = "confluent" }
kafka-streams-avro-serde = { group = "io.confluent", name = "kafka-streams-avro-serde", version.ref = "confluent" }
kafka-streams-protobuf-serde = { group = "io.confluent", name = "kafka-streams-protobuf-serde", version.ref = "confluent" }
kafka-streams-jsonSchema-serde = { group = "io.confluent", name = "kafka-streams-json-schema-serde", version.ref = "confluent" }
kafka-connect-avro-converter = { group = "io.confluent", name = "kafka-connect-avro-converter", version.ref = "confluent" }
kafka-connect-protobuf-converter = { group = "io.confluent", name = "kafka-connect-protobuf-converter", version.ref = "confluent" }
kafka-connect-jsonSchema-converter = { group = "io.confluent", name = "kafka-connect-json-schema-converter", version.ref = "confluent" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }
jool = { group = "org.jooq", name = "jool", version = "0.9.15" }

junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version = "3.27.6" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
logcaptor = { group = "io.github.hakky54", name = "logcaptor", version = "2.12.1" }

[plugins]
release = { id = "com.bakdata.release", version = "1.11.1" }
sonar = { id = "com.bakdata.sonar", version = "1.11.1" }
sonatype = { id = "com.bakdata.sonatype", version = "1.11.1" }
lombok = { id = "io.freefair.lombok", version = "8.14" }
